version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ucni_projekt
    ports:
      - "5433:5432"
  storitev:
    image: mjamsek/ucni-projekt:latest
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5433/ucni_projekt
    ports:
      - "8080:8080"
    depends_on:
      - postgres
