kumuluzee:
  name: vprasanja-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8080
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15
  datasources:
    - jndi-name: jdbc/baza
      connection-url: jdbc:postgresql://localhost:5432/ucni_projekt
      username: postgres
      password: postgres
      max-pool-size: 20
  openapi:
    ui:
      enabled: true

rest-config:
  string-property: Tork
  boolean-property: true
  integer-property: 23