apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files (x86)\Kubernetes\kompose.exe convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: angular
  name: angular
spec:
  type: NodePort
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
    nodePort: 30042
  selector:
    io.kompose.service: angular
status:
  loadBalancer: {}
