apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files (x86)\Kubernetes\kompose-windows-amd64.exe convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: etcd
  name: etcd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: etcd
    spec:
      containers:
      - args:
        - /usr/local/bin/etcd
        - -name
        - etcd
        - --data-dir
        - /etcd_data
        - -advertise-client-urls
        - http://etcd:2379
        - -listen-client-urls
        - http://0.0.0.0:2379
        - -initial-advertise-peer-urls
        - http://etcd:2380
        - -listen-peer-urls
        - http://0.0.0.0:2380
        - -initial-cluster
        - etcd=http://etcd:2380
        - -initial-cluster-token
        - my-etcd-token
        - -initial-cluster-state
        - new
        - -cors="*"
        image: quay.io/coreos/etcd:latest
        name: etcd
        ports:
        - containerPort: 2379
        resources: {}
        volumeMounts:
        - mountPath: /etcd_data
          name: etcd
      restartPolicy: Always
      volumes:
      - name: etcd
        persistentVolumeClaim:
          claimName: etcd
status: {}
